### ISSUE TITLE
Improvements on charts

### ISSUE THREAD

**Issue by danielfdsilva** [global-electrification-platform/explorer#134]
WB feedback

**Bar Chart visualization**
- For second time step- clearly communicate cumulative vs additional
- People as percentage of total population
- Added Capacity as percentage of base
- In first time-step, add un-fulfilled people (see #156)
  - Grey locations on map?
  - Grey numbers in the charts?

**Comment by alekordESA** [comment]
**For second time step- clearly communicate cumulative vs additional**
(This also informs #144 )

There is a mix of additional and cumulative in the second time step indeed. ```People affected``` is clearly cumulative as it sums to the total population of the country in 2030. In contrary ```Investment required``` and ```Added Capacity``` are additional to the time step 2025-2030.

**Option 1** 
In this case, we make results for ```Investment required``` and ```Added Capacity``` in the second time step cumulative. Also instead of ```People affected``` we can use ```People connected```. So the summaries will be calculated as follows:

2025
```PEOPLE CONNECTED = Pop2025 x ElecStatusIn2025```
```INVESTMENT REQUIRED = InvestmentCost2025 x ElecStatusIn2025```
```ADDED CAPACITY = NewCapacity2025 x ElecStatusIn2025 ```

2030
```PEOPLE CONNECTED = Pop2030 x ElecStatusIn2030```
```INVESTMENT REQUIRED = InvestmentCost2025 x ElecStatusIn2025 + InvestmentCost2030 x ElecStatusIn2030```
```ADDED CAPACITY = NewCapacity2025 x ElecStatusIn2025 + NewCapacity2030 x ElecStatusIn2030```

**Note!** ```ElecStatusIn2030``` is always equal to 1 but I add here for consistency.

**Note!** ```PEOPLE CONNECTED``` in 2025 also includes people that had electricity in the base year; not only new connections.

**Option 2** 
In case we want to make everything additional then instead of ```People affected``` we can use ```New connections``` which will indicate only the number of newly electrified people each time step. So the summaries will be calculated as follows:

2025
```NEW CONNECTIONS = NewConnections2025 x ElecStatusIn2025 ```
```INVESTMENT REQUIRED = InvestmentCost2025 x ElecStatusIn2025 ```
```ADDED CAPACITY = NewCapacity2025 x ElecStatusIn2025 ```

2030
```NEW CONNECTIONS = NewConnections2030 x ElecStatusIn2030 ```
```INVESTMENT REQUIRED = InvestmentCost2030 x ElecStatusIn2030 ```
```ADDED CAPACITY = NewCapacity2030 x ElecStatusIn2030 ```

**Note!** that summary title shall also be changed to something like ```RESULTS FOR 2018-2025``` and ```RESULTS FOR 2025-2030``` respectively. 

**Note!** in that case cumulative summaries can be provided in a separate table either calculated as in Option 1 or by using the summary.csv files we provide for each scenario (if easier?).

@bpstewar @Dimitrismentis your thoughts? @vgeorge @danielfdsilva let me know if you think I am missing something here; which approach you think is more sensible?

**Comment by alekordESA** [comment]
**People as percentage of total population**
Summaries of ```People connected``` or  ```New connections``` can be calculated as per previous comment; Then population percentages can be calculated using total population from ```Pop2025``` and ```Pop2030``` respectively, no? 

@bpstewar Do we want percentage for the aggregate population only or for all technologies as well?

**Comment by alekordESA** [comment]
**Added Capacity as percentage of base**
This percentage cannot be calculated based on data currently available in the result files. A solution  I see is that we import current installed capacity as a number - and calculate the percentage increase based on this value. Result might look like this:

2025
```Capacity increase (%) = NewCapacity2025 x ElecStatusIn2025 / InstalledCapacity2018```

2030
```Capacity increase (%) = (NewCapacity2025 x ElecStatusIn2025 + NewCapacity2030 x ElecStatusIn2030) / InstalledCapacity2018```

```InstalledCapacity2018``` can be retrieved from [IEA](https://www.eia.gov/beta/international/data/browser/#/?pa=0000000000000000000004&c=ruvvvvvfvtvnvv1urvvvvfvvvvvvfvvvou20evvvvvvvvvnvvuvo&ct=0&tl_id=2-A&vs=INTL.2-7-AFG-MK.A&cy=2000&vo=0&v=H&end=2016).

@bpstewar thoughts?

**Comment by Dimitrismentis** [comment]
@alekordESA I think option 2 is more sensible to show, i.e the amount of people that are getting connected using the various technologies. 

One comment we 've received often in the previous apps regards the New connections. Users think we refer to number of connections (households) and not number of people. Can we rename to avoid this reasonable confusion? Maybe "People connected since 2018" or "People connected (new connections) or New connections (number of people) or something smarter.

**Comment by vgeorge** [comment]
The percentage value can be calculated at the interface if absolute values for each timestep are available in scenarios files. It would be necessary to include `InstalledCapacityBaseYear` and` PopulationBaseYear`. I suggest using generic name for the base year, as in the future it might not be 2018.

@alekordESA This issue is kind of a blocker now, as we will need to perform changes at the ingest CLI and the web interface before ingesting data, so it would be to have a definition soon.

Another thing, I moved the feedback about map style of unfulfilled clusters to an specific issue: https://github.com/developmentseed/gep-explorer/issues/156

**Comment by ricardomestre** [comment]
Here's a proposal containing two solutions for showing the total population on the charts:

1. With absolute values: https://sketch.cloud/s/v1K7J/a/zGQeko
2. With relative values: https://sketch.cloud/s/v1K7J/a/ZygQpx

**Comment by Dimitrismentis** [comment]
@alekordESA @bpstewar @vgeorge @ricardomestre 
Showing two values (42 out of 84 in this case) in a chart with two colours may be confusing for the users. They may think 42 refers to one colour (grid) and 84 to the other (stand alone PV) or both. Not very intuitive. 
I would keep one number and modify the title of the graph to make it more clear as suggested earlier on.

**Comment by bpstewar** [comment]
@Dimitrismentis we need to include the total population somewhere in that chart area, but I agree having the two numbers is a bit confusing - maybe the relative measure would be better

**Comment by Dimitrismentis** [comment]
@bpstewar Indeed. It is important to show the total population plus some other relevant indicators one could pull from WB online database. e.g. elec. rates. 

Partly related to this issue: 
Here is what was done previously with a simple country overview http://electrification.energydata.info/model/?iso3=TZA&mode=technology (this was an addition based on feedback we received multiple times from users that were missing this high level country information from the initial UNDESA elec. app.

**Comment by alekordESA** [comment]
@bpstewar shall we proceed with the [second option](https://sketch.cloud/s/v1K7J/a/ZygQpx) then for now?

@Dimitrismentis @bpstewar additional relevant indicators can be included in the 1-pager descriptor we generate per country. These are available per model on S3 (example available [here.](https://drive.google.com/drive/folders/18BCb9CqVtpueUjAMXaL07LbcXMBoIt_g?usp=sharing))

**Comment by vgeorge** [comment]
As discussed with @alekordESA, we will use the field `PopStartYear` as base population value to calculate the total population displayed on the chart. 

@danielfdsilva The PR https://github.com/global-electrification-platform/data-service/pull/60 is arealdy including this information in the cluster summary.

**Comment by vgeorge** [comment]
Had a talk today with @alekordESA to clarify the approach here. Key points:

- Total population on the chart should be calculated from time stepped `Pop<year>` (eg. Pop2025, Pop2030) values, which are already available in the summary. `PopStartedYear` will be dropped;
- "People Connected" at the chart should be an aggregate of `PeopleConnect<year>` property, available in the summary. This property is derived from other two, as the output files do not include it at the moment. The ingest process will add to the summary the field `PeopleConnected<year>`, according to this expression:

```
PeopleConnected<year> = NewConnections<year> * ElecStatusIn<year>
```

I'm implementing this change now as we need it for preparing the data for the workshop in time. Please let us know if there is any comment.

**Comment by alekordESA** [comment]
@vgeorge ```Pop<year>``` will give the population in the according year. However, if you are using the formula as above you will only include the newly electrified population in the summary; that is, you ll miss the people that are already electrified. We want to include these in the final summary no? This can be provided by equation ```PEOPLE CONNECTED = Pop2025 x ElecStatusIn2025``` as per my comment earlier. Is my understanding wrong? (please discard if so).

**Comment by vgeorge** [comment]
I see. At the end we are going for option 1, which is cumulative.  I'll proceed implementing using `Pop`, instead of `NewConnections`:

```
PeopleConnected<year> = Pop<year> x ElecStatusIn<year>
```

**Comment by akorkovelos** [comment]
@vgeorge quick on the summary charts. Tag shall change from ```Grid extension``` to just ```Grid``` on the right side bar of the explorer.

**Comment by vgeorge** [comment]
@akorkovelos, I've opened an issue at the data service to address renaming "Grid extension", as the labels are provided from there. https://github.com/global-electrification-platform/data-service/issues/72

I'm closing this issue in favor of https://github.com/global-electrification-platform/explorer/issues/188, which specifically address the remaining issue of adding baseline information.
